### ISSUE TITLE
Feature Request: Open HS window on active monitor

### ISSUE THREAD

**Issue by satchellbc** [JSSatchell/HyperSearch#1]
Not sure if this is even possible, but I use multiple monitors and my internet browser is most often on my second screen. Would it be possible to have HS open on the "active" monitor, i.e. where the mouse currently is or where the last active program is?

**Comment by JSSatchell** [comment]
Good thought, I'll look into it. Thanks!

**Comment by JSSatchell** [comment]
Fixed, will be addressed in next release.
